### ISSUE TITLE
Add queue mechanism for sendChatbotReply and markChatAsRead

### ISSUE THREAD

**Issue by raosan** [hyperjumptech/whatsapp-chatbot-connector#13]
To prevent timeout when returning webhooks, we need to shorten the response time. One way is using queue like [Rabbit MQ](https://www.rabbitmq.com/)

**Comment by irwansyahwii** [comment]
Can I take this one @raosan ? :)

**Comment by raosan** [comment]
> Can I take this one @raosan ? :)

Yup, go for it. Take note that i change the suggestion to use rabbit mq
