### ISSUE TITLE
Change axios to node fetcher

### ISSUE THREAD

**Issue by raosan** [hyperjumptech/whatsapp-chatbot-connector#6]

**Comment by irwansyahwii** [comment]
Can I take this since @raosan  since I already worked similarly and created PR on Monika [here](https://github.com/hyperjumptech/monika/pull/1310)?

**Comment by raosan** [comment]
> Can I take this since @raosan since I already worked similarly and created PR on Monika [here](https://github.com/hyperjumptech/monika/pull/1310)?

Sure, with pleasure

**Comment by raosan** [comment]
Closed this as it is not really needed
